name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform_name: Linux
            artifact_name: coffeegrindsize-linux
            executable_ext: ''
          - os: windows-latest
            platform_name: Windows
            artifact_name: coffeegrindsize-windows
            executable_ext: '.exe'
          - os: macos-latest
            platform_name: macOS
            artifact_name: coffeegrindsize-macos
            executable_ext: '.app'

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable (Windows/Linux)
      if: matrix.os != 'macos-latest'
      run: |
        pyinstaller --name=coffeegrindsize --windowed --onefile --icon=NONE coffeegrindsize.py

    - name: Build executable (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --name=coffeegrindsize --windowed --onedir coffeegrindsize.py

    - name: Package for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd dist
        tar -czf coffeegrindsize-linux.tar.gz coffeegrindsize
        cd ..

    - name: Package for Windows
      if: matrix.os == 'windows-latest'
      run: |
        cd dist
        Compress-Archive -Path coffeegrindsize.exe -DestinationPath coffeegrindsize-windows.zip
        cd ..

    - name: Package for macOS
      if: matrix.os == 'macos-latest'
      run: |
        cd dist
        # Create a zip of the .app bundle
        zip -r coffeegrindsize-macos.zip coffeegrindsize.app
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          dist/coffeegrindsize-linux.tar.gz
          dist/coffeegrindsize-windows.zip
          dist/coffeegrindsize-macos.zip
        if-no-files-found: ignore

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/coffeegrindsize-linux/coffeegrindsize-linux.tar.gz
          artifacts/coffeegrindsize-windows/coffeegrindsize-windows.zip
          artifacts/coffeegrindsize-macos/coffeegrindsize-macos.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
